// ~200 termos médicos frequentes para residência médica
// Ordenados do mais longo para o mais curto para matching correto
export const MEDICAL_TERMS: string[] = [
  // Cardiologia
  "insuficiência cardíaca congestiva",
  "insuficiência cardíaca",
  "infarto agudo do miocárdio",
  "fibrilação atrial",
  "flutter atrial",
  "hipertensão arterial sistêmica",
  "hipertensão arterial",
  "estenose aórtica",
  "insuficiência mitral",
  "endocardite infecciosa",
  "pericardite",
  "tamponamento cardíaco",
  "cardiomiopatia dilatada",
  "cardiomiopatia hipertrófica",
  "síndrome coronariana aguda",
  "angina instável",
  "bloqueio atrioventricular",
  "taquicardia ventricular",
  "dissecção de aorta",
  "trombose venosa profunda",
  "tromboembolismo pulmonar",
  "embolia pulmonar",

  // Pneumologia
  "doença pulmonar obstrutiva crônica",
  "pneumonia adquirida na comunidade",
  "pneumonia nosocomial",
  "síndrome do desconforto respiratório agudo",
  "pneumotórax hipertensivo",
  "derrame pleural",
  "asma brônquica",
  "bronquiectasia",
  "fibrose pulmonar",
  "tuberculose pulmonar",
  "pneumotórax",
  "tuberculose",
  "pneumonia",
  "asma",
  "DPOC",
  "SDRA",

  // Neurologia
  "acidente vascular cerebral isquêmico",
  "acidente vascular cerebral hemorrágico",
  "acidente vascular cerebral",
  "hemorragia subaracnóidea",
  "meningite bacteriana",
  "encefalite viral",
  "esclerose múltipla",
  "doença de Parkinson",
  "doença de Alzheimer",
  "epilepsia",
  "síndrome de Guillain-Barré",
  "miastenia gravis",
  "hipertensão intracraniana",
  "neuropatia periférica",
  "cefaleia tensional",
  "enxaqueca",
  "meningite",
  "AVC",

  // Gastroenterologia
  "doença do refluxo gastroesofágico",
  "úlcera péptica",
  "doença inflamatória intestinal",
  "doença de Crohn",
  "retocolite ulcerativa",
  "cirrose hepática",
  "hepatite viral",
  "hepatite autoimune",
  "pancreatite aguda",
  "pancreatite crônica",
  "colecistite aguda",
  "colelitíase",
  "apendicite aguda",
  "obstrução intestinal",
  "hemorragia digestiva alta",
  "hemorragia digestiva baixa",
  "síndrome do intestino irritável",
  "esteatose hepática",
  "apendicite",
  "cirrose",
  "DRGE",

  // Endocrinologia
  "diabetes mellitus tipo 1",
  "diabetes mellitus tipo 2",
  "diabetes mellitus",
  "cetoacidose diabética",
  "hipotireoidismo",
  "hipertireoidismo",
  "doença de Graves",
  "tireoidite de Hashimoto",
  "síndrome de Cushing",
  "insuficiência adrenal",
  "feocromocitoma",
  "hiperaldosteronismo primário",
  "nódulo tireoideano",
  "diabetes insipidus",
  "hipoglicemia",

  // Nefrologia
  "insuficiência renal aguda",
  "doença renal crônica",
  "insuficiência renal crônica",
  "síndrome nefrótica",
  "síndrome nefrítica",
  "glomerulonefrite",
  "pielonefrite",
  "infecção do trato urinário",
  "litíase renal",
  "necrose tubular aguda",
  "nefropatia diabética",

  // Hematologia
  "anemia falciforme",
  "anemia ferropriva",
  "anemia megaloblástica",
  "leucemia mieloide aguda",
  "leucemia linfoide aguda",
  "linfoma de Hodgkin",
  "linfoma não-Hodgkin",
  "coagulação intravascular disseminada",
  "púrpura trombocitopênica",
  "hemofilia",
  "mieloma múltiplo",
  "policitemia vera",

  // Infectologia
  "sepse",
  "choque séptico",
  "HIV/AIDS",
  "sífilis",
  "dengue",
  "leptospirose",
  "malária",
  "leishmaniose visceral",
  "doença de Chagas",
  "esquistossomose",
  "toxoplasmose",
  "herpes zóster",
  "COVID-19",

  // Cirurgia
  "abdome agudo",
  "hérnia inguinal",
  "hérnia incisional",
  "colecistectomia",
  "trauma abdominal",
  "trauma torácico",
  "politrauma",
  "choque hipovolêmico",
  "choque cardiogênico",

  // Ginecologia e Obstetrícia
  "pré-eclâmpsia",
  "eclâmpsia",
  "síndrome HELLP",
  "placenta prévia",
  "descolamento prematuro de placenta",
  "gravidez ectópica",
  "endometriose",
  "mioma uterino",
  "síndrome dos ovários policísticos",
  "doença inflamatória pélvica",
  "diabetes gestacional",
  "trabalho de parto prematuro",
  "rotura prematura de membranas",

  // Pediatria
  "bronquiolite",
  "croup",
  "doença de Kawasaki",
  "estenose hipertrófica do piloro",
  "intussuscepção",
  "icterícia neonatal",
  "sepse neonatal",
  "convulsão febril",
  "desidratação",

  // Reumatologia
  "artrite reumatoide",
  "lúpus eritematoso sistêmico",
  "febre reumática",
  "gota",
  "espondilite anquilosante",
  "vasculite",
  "esclerodermia",

  // Dermatologia
  "psoríase",
  "dermatite atópica",
  "urticária",
  "celulite",
  "erisipela",

  // Psiquiatria
  "depressão maior",
  "transtorno bipolar",
  "esquizofrenia",
  "transtorno de ansiedade generalizada",
  "síndrome de burnout",

  // Medicina Preventiva
  "hipertensão gestacional",
  "rastreamento neonatal",

  // Oncologia
  "neoplasia maligna",
  "carcinoma de células escamosas",
  "adenocarcinoma",
  "câncer de mama",
  "câncer de pulmão",
  "câncer colorretal",
  "câncer de próstata",
  "câncer gástrico",
  "câncer de colo uterino",
  "câncer de pâncreas",
  "câncer de fígado",
  "câncer de bexiga",
  "câncer de tireoide",
  "melanoma maligno",
  "quimioterapia",
  "radioterapia",
  "imunoterapia",
  "terapia-alvo",
  "estadiamento TNM",
  "metástase",
  "síndrome paraneoplásica",
  "marcador tumoral",
  "cuidados paliativos",
  "rastreamento oncológico",
  "oncologia",

  // Fisiologia
  "potencial de ação",
  "potencial de repouso",
  "débito cardíaco",
  "volume sistólico",
  "fração de ejeção",
  "pressão oncótica",
  "pressão hidrostática",
  "filtração glomerular",
  "taxa de filtração glomerular",
  "clearance de creatinina",
  "equilíbrio ácido-base",
  "hemodinâmica",
  "termorregulação",
  "difusão alveolar",
  "ventilação alveolar",
  "contração muscular",
  "acoplamento excitação-contração",
  "sinapse",
  "neurotransmissor",
  "barorreceptor",
  "quimiorreceptor",
  "sistema renina-angiotensina-aldosterona",
  "hormônio antidiurético",
  "peptídeo natriurético atrial",

  // Bioquímica
  "glicólise",
  "gliconeogênese",
  "ciclo de Krebs",
  "ciclo do ácido cítrico",
  "fosforilação oxidativa",
  "cadeia transportadora de elétrons",
  "beta-oxidação",
  "cetogênese",
  "corpos cetônicos",
  "ciclo da ureia",
  "síntese de ácidos graxos",
  "hemoglobina glicada",
  "enzima alostérica",
  "coenzima A",
  "NAD+",
  "NADH",
  "FADH2",
  "acetil-CoA",
  "piruvato desidrogenase",
  "erro inato do metabolismo",
  "fenilcetonúria",
  "galactosemia",
  "doença de Gaucher",
  "bioenergética",

  // Histologia
  "tecido epitelial",
  "tecido conjuntivo",
  "tecido muscular",
  "tecido nervoso",
  "hematoxilina e eosina",
  "coloração histológica",
  "lâmina histológica",
  "microscopia óptica",
  "microscopia eletrônica",

  // Embriologia
  "gastrulação",
  "neurulação",
  "organogênese",
  "blastocisto",
  "tubo neural",
  "somito",
  "teratogênese",
  "malformação congênita",
  "placenta",
  "cordão umbilical",

  // Microbiologia
  "gram positivo",
  "gram negativo",
  "antibiograma",
  "cultura bacteriana",
  "biofilme",
  "virulência",
  "bacteremia",
  "resistência bacteriana",

  // Imunologia
  "linfócito T",
  "linfócito B",
  "imunoglobulina",
  "citocina",
  "sistema complemento",
  "hipersensibilidade",
  "autoimunidade",
  "imunodeficiência",
  "complexo de histocompatibilidade",
  "resposta imune inata",
  "resposta imune adaptativa",

  // Parasitologia
  "ciclo biológico",
  "helminto",
  "protozoário",
  "vetor biológico",
  "giardíase",
  "amebíase",
  "ancilostomíase",
  "ascaridíase",
  "teníase",
  "cisticercose",

  // Genética Médica
  "cariótipo",
  "herança autossômica",
  "herança ligada ao X",
  "trissomia",
  "síndrome de Down",
  "síndrome de Turner",
  "síndrome de Klinefelter",
  "aconselhamento genético",
  "sequenciamento genético",
  "epigenética",

  // Patologia
  "necrose coagulativa",
  "necrose liquefativa",
  "inflamação aguda",
  "inflamação crônica",
  "granuloma",
  "displasia",
  "metaplasia",
  "hiperplasia",
  "atrofia",
  "apoptose",
  "amiloidose",
  "trombo",
  "êmbolo",
  "infarto",
].sort((a, b) => b.length - a.length); // Longest first for greedy matching
