export const FACULDADES = [
  "Arthur Sá Earp Neto (FASE)",
  "Estácio",
  "FMP/Fase",
  "FTESM",
  "IBMR",
  "PUC-Rio",
  "Souza Marques",
  "UERJ",
  "UFF",
  "UFRJ",
  "UNESA",
  "UNIFESO",
  "UNIFOA",
  "UNIG",
  "UNIGRANRIO",
  "UNIRIO",
  "UniRedentor",
  "Universidade Castelo Branco",
  "Universidade Vassouras",
  "Outra",
];
