export const FACULDADES = [
  // Federais
  "FURG – Universidade Federal do Rio Grande",
  "UFABC – Universidade Federal do ABC",
  "UFAC – Universidade Federal do Acre",
  "UFAL – Universidade Federal de Alagoas",
  "UFAM – Universidade Federal do Amazonas",
  "UFBA – Universidade Federal da Bahia",
  "UFC – Universidade Federal do Ceará",
  "UFCA – Universidade Federal do Cariri",
  "UFCG – Universidade Federal de Campina Grande",
  "UFCSPA – Universidade Federal de Ciências da Saúde de Porto Alegre",
  "UFERSA – Universidade Federal Rural do Semi-Árido",
  "UFES – Universidade Federal do Espírito Santo",
  "UFF – Universidade Federal Fluminense",
  "UFG – Universidade Federal de Goiás",
  "UFGD – Universidade Federal da Grande Dourados",
  "UFJF – Universidade Federal de Juiz de Fora",
  "UFLA – Universidade Federal de Lavras",
  "UFMA – Universidade Federal do Maranhão",
  "UFMG – Universidade Federal de Minas Gerais",
  "UFMS – Universidade Federal de Mato Grosso do Sul",
  "UFMT – Universidade Federal de Mato Grosso",
  "UFOB – Universidade Federal do Oeste da Bahia",
  "UFOP – Universidade Federal de Ouro Preto",
  "UFPA – Universidade Federal do Pará",
  "UFPB – Universidade Federal da Paraíba",
  "UFPE – Universidade Federal de Pernambuco",
  "UFPel – Universidade Federal de Pelotas",
  "UFPI – Universidade Federal do Piauí",
  "UFPR – Universidade Federal do Paraná",
  "UFRB – Universidade Federal do Recôncavo da Bahia",
  "UFRGS – Universidade Federal do Rio Grande do Sul",
  "UFRJ – Universidade Federal do Rio de Janeiro",
  "UFRN – Universidade Federal do Rio Grande do Norte",
  "UFRPE – Universidade Federal Rural de Pernambuco",
  "UFRRJ – Universidade Federal Rural do Rio de Janeiro",
  "UFS – Universidade Federal de Sergipe",
  "UFSC – Universidade Federal de Santa Catarina",
  "UFSCar – Universidade Federal de São Carlos",
  "UFSJ – Universidade Federal de São João del-Rei",
  "UFSM – Universidade Federal de Santa Maria",
  "UFT – Universidade Federal do Tocantins",
  "UFTM – Universidade Federal do Triângulo Mineiro",
  "UFU – Universidade Federal de Uberlândia",
  "UFV – Universidade Federal de Viçosa",
  "UFVJM – Universidade Federal dos Vales do Jequitinhonha e Mucuri",
  "UnB – Universidade de Brasília",
  "UNIFAL – Universidade Federal de Alfenas",
  "UNIFAP – Universidade Federal do Amapá",
  "UNIFESP – Universidade Federal de São Paulo",
  "UNILA – Universidade Federal da Integração Latino-Americana",
  "UNILAB – Universidade da Integração Internacional da Lusofonia Afro-Brasileira",
  "UNIR – Universidade Federal de Rondônia",
  "UNIRIO – Universidade Federal do Estado do Rio de Janeiro",
  "UNIVASF – Universidade Federal do Vale do São Francisco",

  // Estaduais
  "UEAP – Universidade do Estado do Amapá",
  "UECE – Universidade Estadual do Ceará",
  "UEG – Universidade Estadual de Goiás",
  "UEL – Universidade Estadual de Londrina",
  "UEM – Universidade Estadual de Maringá",
  "UEMA – Universidade Estadual do Maranhão",
  "UEMS – Universidade Estadual de Mato Grosso do Sul",
  "UEPA – Universidade do Estado do Pará",
  "UEPB – Universidade Estadual da Paraíba",
  "UEPG – Universidade Estadual de Ponta Grossa",
  "UERJ – Universidade do Estado do Rio de Janeiro",
  "UERR – Universidade Estadual de Roraima",
  "UESB – Universidade Estadual do Sudoeste da Bahia",
  "UESC – Universidade Estadual de Santa Cruz",
  "UESPI – Universidade Estadual do Piauí",
  "UEZO – Centro Universitário Estadual da Zona Oeste",
  "UNEB – Universidade do Estado da Bahia",
  "UNEMAT – Universidade do Estado de Mato Grosso",
  "UNESP – Universidade Estadual Paulista",
  "UNICAMP – Universidade Estadual de Campinas",
  "UNICENTRO – Universidade Estadual do Centro-Oeste",
  "UNIOESTE – Universidade Estadual do Oeste do Paraná",
  "UNITINS – Universidade Estadual do Tocantins",
  "USP – Universidade de São Paulo",

  // Privadas / Comunitárias
  "Albert Einstein – Faculdade de Medicina Albert Einstein",
  "Anhembi Morumbi – Universidade Anhembi Morumbi",
  "Arthur Sá Earp Neto (FASE)",
  "Atenas – UniAtenas",
  "CESUPA – Centro Universitário do Pará",
  "Estácio – Universidade Estácio de Sá",
  "FMJ – Faculdade de Medicina de Jundiaí",
  "FMABC – Faculdade de Medicina do ABC",
  "FMP/Fase – Faculdade de Medicina de Petrópolis",
  "FTESM – Faculdade de Tecnologia e Ciências de Salvador",
  "IBMR – Centro Universitário IBMR",
  "Mackenzie – Universidade Presbiteriana Mackenzie",
  "PUC Campinas – Pontifícia Universidade Católica de Campinas",
  "PUC Goiás – Pontifícia Universidade Católica de Goiás",
  "PUC Minas – Pontifícia Universidade Católica de Minas Gerais",
  "PUC-PR – Pontifícia Universidade Católica do Paraná",
  "PUC-Rio – Pontifícia Universidade Católica do Rio de Janeiro",
  "PUC-RS – Pontifícia Universidade Católica do Rio Grande do Sul",
  "PUC-SP – Pontifícia Universidade Católica de São Paulo",
  "Santa Casa de SP – Faculdade de Ciências Médicas da Santa Casa de SP",
  "Souza Marques – Fundação Técnico-Educacional Souza Marques",
  "UCB – Universidade Católica de Brasília",
  "UCPEL – Universidade Católica de Pelotas",
  "UCS – Universidade de Caxias do Sul",
  "ULBRA – Universidade Luterana do Brasil",
  "UMC – Universidade de Mogi das Cruzes",
  "UNESA – Universidade Estácio de Sá",
  "UNIFESO – Centro Universitário Serra dos Órgãos",
  "UNIFOA – Centro Universitário de Volta Redonda",
  "UNIG – Universidade Iguaçu",
  "UNIGRANRIO – Universidade do Grande Rio",
  "UNIJUÍ – Universidade Regional do Noroeste do Estado do RS",
  "UNIME – União Metropolitana de Educação e Cultura",
  "UNINASSAU – Centro Universitário Maurício de Nassau",
  "UNINOVE – Universidade Nove de Julho",
  "UNIP – Universidade Paulista",
  "UniRedentor – Centro Universitário Redentor",
  "UNISA – Universidade de Santo Amaro",
  "UNISINOS – Universidade do Vale do Rio dos Sinos",
  "UNIVALI – Universidade do Vale do Itajaí",
  "UNIVILLE – Universidade da Região de Joinville",
  "Universidade Castelo Branco",
  "Universidade de Vassouras",
  "UPF – Universidade de Passo Fundo",

  // Última opção
  "Outra",
];
