export const SPECIALTY_SUBTOPICS: Record<string, string[]> = {
  // Ciclo Básico
  "Anatomia": ["Neuroanatomia", "Anatomia do Tórax", "Anatomia do Abdome", "Anatomia Musculoesquelética", "Anatomia Vascular"],
  "Bioquímica": ["Metabolismo de Carboidratos", "Metabolismo de Lipídios", "Metabolismo de Proteínas", "Bioenergética", "Vitaminas e Cofatores"],
  "Embriologia": ["Embriologia Cardíaca", "Embriologia do SNC", "Malformações Congênitas", "Embriologia do TGI"],
  "Farmacologia": ["Farmacocinética", "Farmacodinâmica", "Antibióticos", "Anti-hipertensivos", "Analgésicos e Anti-inflamatórios", "Psicofármacos", "Quimioterápicos"],
  "Fisiologia": ["Fisiologia Cardiovascular", "Fisiologia Respiratória", "Fisiologia Renal", "Fisiologia Endócrina", "Neurofisiologia", "Fisiologia Gastrointestinal"],
  "Genética Médica": ["Herança Mendeliana", "Cromossomopatias", "Erros Inatos do Metabolismo", "Aconselhamento Genético"],
  "Histologia": ["Tecido Epitelial", "Tecido Conjuntivo", "Tecido Nervoso", "Tecido Muscular"],
  "Imunologia": ["Imunidade Inata", "Imunidade Adaptativa", "Autoimunidade", "Imunodeficiências", "Hipersensibilidade", "Transplantes"],
  "Microbiologia": ["Bacteriologia", "Virologia", "Micologia", "Resistência Bacteriana"],
  "Parasitologia": ["Protozoários", "Helmintos", "Doença de Chagas", "Malária", "Leishmaniose", "Esquistossomose"],
  "Patologia": ["Inflamação", "Neoplasias", "Distúrbios Hemodinâmicos", "Patologia Ambiental", "Imunopatologia"],
  "Semiologia": ["Propedêutica Cardiovascular", "Propedêutica Respiratória", "Propedêutica Abdominal", "Exame Neurológico", "Anamnese"],

  // Ciclo Clínico
  "Angiologia": ["Doença Arterial Periférica", "Trombose Venosa Profunda", "Aneurisma de Aorta", "Varizes", "Insuficiência Venosa", "Linfangite e Erisipela"],
  "Cardiologia": ["IAM com Supra de ST", "IAM sem Supra", "Insuficiência Cardíaca", "Arritmias", "Valvopatias", "Hipertensão Arterial", "Endocardite", "Pericardite", "Cardiopatias Congênitas", "Miocardiopatias", "Crise Hipertensiva", "Doença Coronariana", "Síndromes Coronarianas Agudas"],
  "Dermatologia": ["Dermatoses Infecciosas", "Dermatoses Autoimunes", "Câncer de Pele", "Hanseníase", "Psoríase", "Dermatite Atópica", "Lesões Elementares da Pele", "Piodermites", "Dermatoviroses", "Dermatozoonoses"],
  "Endocrinologia": ["Diabetes Mellitus", "Cetoacidose Diabética", "Tireoidopatias", "Síndrome de Cushing", "Insuficiência Adrenal", "Distúrbios da Paratireoide", "Obesidade", "Síndrome Hiperosmolar", "Dislipidemias"],
  "Gastroenterologia": ["Doença do Refluxo", "Úlcera Péptica", "Doença Inflamatória Intestinal", "Hepatites Virais", "Cirrose Hepática", "Pancreatite", "Doença Celíaca", "Hemorragia Digestiva", "Distúrbios Motores do Esôfago", "Dispepsia e Gastrite", "Doença Diverticular"],
  "Hematologia": ["Anemias", "Leucemias", "Linfomas", "Coagulopatias", "Trombocitopenias", "Hemoglobinopatias", "Distúrbios da Hemostasia"],
  "Infectologia": ["HIV/AIDS", "Tuberculose", "Meningites", "Sepse", "Infecções Oportunistas", "Dengue", "Leptospirose", "Hepatites", "COVID-19", "Endocardite Infecciosa", "Arboviroses", "Resistência Antimicrobiana"],
  "Nefrologia": ["Insuficiência Renal Aguda", "Doença Renal Crônica", "Glomerulopatias", "Distúrbios Hidroeletrolíticos", "Distúrbios Ácido-Base", "Síndrome Nefrótica", "Síndrome Nefrítica"],
  "Neurologia": ["AVC Isquêmico", "AVC Hemorrágico", "Epilepsia", "Cefaléias", "Esclerose Múltipla", "Parkinson", "Neuropatias Periféricas", "Meningites", "Demências", "Neuropatia Diabética"],
  "Oftalmologia": ["Glaucoma", "Catarata", "Retinopatia Diabética", "Descolamento de Retina", "Conjuntivites", "Trauma Ocular"],
  "Oncologia": ["Câncer de Mama", "Câncer de Pulmão", "Câncer Colorretal", "Câncer Gástrico", "Estadiamento TNM", "Síndromes Paraneoplásicas", "Neutropenia Febril", "Câncer de Endométrio", "Câncer de Ovário"],
  "Ortopedia": ["Fraturas", "Luxações", "Osteomielite", "Artrose", "Lombalgia", "Trauma Musculoesquelético", "Lesões Ligamentares"],
  "Otorrinolaringologia": ["Otite Média", "Sinusite", "Faringite", "Tonsilite", "Vertigem", "Perda Auditiva"],
  "Pneumologia": ["Asma", "DPOC", "Pneumonia", "Tuberculose Pulmonar", "Tromboembolismo Pulmonar", "Derrame Pleural", "Câncer de Pulmão", "SDRA", "Fibrose Pulmonar", "Propedêutica Respiratória", "Micoses Pulmonares", "Pneumonia Nosocomial"],
  "Psiquiatria": ["Depressão", "Transtorno Bipolar", "Esquizofrenia", "Transtornos de Ansiedade", "TOC", "TEPT", "Dependência Química", "Emergências Psiquiátricas"],
  "Reumatologia": ["Artrite Reumatoide", "Lúpus Eritematoso Sistêmico", "Espondiloartrites", "Gota", "Vasculites", "Esclerodermia", "Fibromialgia"],
  "Urologia": ["Litíase Renal", "Hiperplasia Prostática", "Câncer de Próstata", "Infecção Urinária", "Trauma Urológico", "Incontinência Urinária"],

  // Internato
  "Cirurgia": ["Abdome Agudo", "Apendicite", "Colecistite", "Hérnias", "Trauma Abdominal", "Trauma Torácico", "Pré e Pós-operatório", "Queimaduras", "Politrauma", "Abdome Agudo Obstrutivo", "Doença Hemorroidária", "Úlcera Perfurada", "Doença Diverticular", "Isquemia Mesentérica", "Fístulas Digestivas"],
  "Ginecologia e Obstetrícia": ["Pré-eclâmpsia", "Eclâmpsia", "Pré-natal", "Trabalho de Parto", "Hemorragias da Gestação", "Infecções na Gestação", "Câncer de Colo", "Endometriose", "SOP", "Climatério", "Placenta Prévia", "DPP", "Diabetes Gestacional", "Distócias", "Cesariana", "Trabalho de Parto Prematuro", "Puerpério", "Anticoncepção", "ISTs na Ginecologia"],
  "Medicina de Emergência": ["PCR e RCP", "Choque", "Intoxicações", "Anafilaxia", "Trauma", "Emergências Hipertensivas", "Cetoacidose Diabética", "Status Epiléptico", "Choque Hipovolêmico"],
  "Medicina Preventiva": ["Epidemiologia", "Vigilância em Saúde", "SUS", "Atenção Primária", "Vacinação", "Saúde do Trabalhador", "Bioestatística", "Estudos Epidemiológicos", "Sistemas de Informação em Saúde", "Indicadores de Saúde", "Níveis de Prevenção", "Notificação Compulsória", "Ética e Bioética Médica", "Determinantes Sociais de Saúde"],
  "Pediatria": ["Neonatologia", "Aleitamento Materno", "Crescimento e Desenvolvimento", "Infecções na Infância", "Asma Infantil", "Bronquiolite", "Doenças Exantemáticas", "Desnutrição", "Imunização", "IVAS", "Pneumonia na Criança", "ITU na Criança", "Tuberculose na Criança", "Piodermites na Criança", "Reanimação Neonatal", "Icterícia Neonatal", "Infecções Congênitas (TORCH)", "Desidratação na Criança", "Meningite na Criança", "Febre sem Foco", "Convulsão Febril"],
  "Terapia Intensiva": ["Ventilação Mecânica", "Sepse e Choque Séptico", "Distúrbios Hidroeletrolíticos", "Sedação e Analgesia", "Monitorização Hemodinâmica", "SDRA", "Nutrição Enteral e Parenteral"],
};
